# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#unstable_features
#unstable_features = true

# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#merge_imports
# merge_imports = true

# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#imports_granularity
#imports_granularity = "Crate"
